spring.application.name: orders-assignment

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/orders-assignment}
    username: ${MYSQL_USER:orders}
    password: ${MYSQL_PASSWORD:pw123}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      idle-timeout: 30000
      pool-name: orders-assignment-pool
      max-lifetime: 1800000
      connection-timeout: 30000



